server:
  port: 0

grpc:
  server:
    port: 59091

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: ru.yandex.practicum.kafka.serializer.serializer.AvroSerializer